# Generated by Django 5.2.3 on 2025-07-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
